// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnapshotReq.proto

#ifndef PROTOBUF_SnapshotReq_2eproto__INCLUDED
#define PROTOBUF_SnapshotReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_SnapshotReq_2eproto();
void protobuf_AssignDesc_SnapshotReq_2eproto();
void protobuf_ShutdownFile_SnapshotReq_2eproto();

class SnapshotReq;

// ===================================================================

class SnapshotReq : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:SnapshotReq) */ {
 public:
  SnapshotReq();
  virtual ~SnapshotReq();

  SnapshotReq(const SnapshotReq& from);

  inline SnapshotReq& operator=(const SnapshotReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const SnapshotReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const SnapshotReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(SnapshotReq* other);

  // implements Message ----------------------------------------------

  inline SnapshotReq* New() const { return New(NULL); }

  SnapshotReq* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const SnapshotReq& from);
  void MergeFrom(const SnapshotReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SnapshotReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 roomId = 1;
  void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  ::google::protobuf::uint32 roomid() const;
  void set_roomid(::google::protobuf::uint32 value);

  // optional fixed32 heroId = 2;
  void clear_heroid();
  static const int kHeroIdFieldNumber = 2;
  ::google::protobuf::uint32 heroid() const;
  void set_heroid(::google::protobuf::uint32 value);

  // optional fixed32 attHeroId = 3;
  void clear_attheroid();
  static const int kAttHeroIdFieldNumber = 3;
  ::google::protobuf::uint32 attheroid() const;
  void set_attheroid(::google::protobuf::uint32 value);

  // optional float accSpeed = 4;
  void clear_accspeed();
  static const int kAccSpeedFieldNumber = 4;
  float accspeed() const;
  void set_accspeed(float value);

  // optional float x = 5;
  void clear_x();
  static const int kXFieldNumber = 5;
  float x() const;
  void set_x(float value);

  // optional float y = 6;
  void clear_y();
  static const int kYFieldNumber = 6;
  float y() const;
  void set_y(float value);

  // optional float vx = 7;
  void clear_vx();
  static const int kVxFieldNumber = 7;
  float vx() const;
  void set_vx(float value);

  // optional float vy = 8;
  void clear_vy();
  static const int kVyFieldNumber = 8;
  float vy() const;
  void set_vy(float value);

  // optional string version = 9;
  void clear_version();
  static const int kVersionFieldNumber = 9;
  const ::std::string& version() const;
  void set_version(const ::std::string& value);
  void set_version(const char* value);
  void set_version(const char* value, size_t size);
  ::std::string* mutable_version();
  ::std::string* release_version();
  void set_allocated_version(::std::string* version);

  // optional string taskId = 10;
  void clear_taskid();
  static const int kTaskIdFieldNumber = 10;
  const ::std::string& taskid() const;
  void set_taskid(const ::std::string& value);
  void set_taskid(const char* value);
  void set_taskid(const char* value, size_t size);
  ::std::string* mutable_taskid();
  ::std::string* release_taskid();
  void set_allocated_taskid(::std::string* taskid);

  // optional fixed64 timestamp = 11;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 11;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:SnapshotReq)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  bool _is_default_instance_;
  ::google::protobuf::uint32 roomid_;
  ::google::protobuf::uint32 heroid_;
  ::google::protobuf::uint32 attheroid_;
  float accspeed_;
  float x_;
  float y_;
  float vx_;
  float vy_;
  ::google::protobuf::internal::ArenaStringPtr version_;
  ::google::protobuf::internal::ArenaStringPtr taskid_;
  ::google::protobuf::uint64 timestamp_;
  mutable int _cached_size_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_SnapshotReq_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_SnapshotReq_2eproto();
  #endif
  friend void protobuf_AssignDesc_SnapshotReq_2eproto();
  friend void protobuf_ShutdownFile_SnapshotReq_2eproto();

  void InitAsDefaultInstance();
  static SnapshotReq* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SnapshotReq

// optional fixed32 roomId = 1;
inline void SnapshotReq::clear_roomid() {
  roomid_ = 0u;
}
inline ::google::protobuf::uint32 SnapshotReq::roomid() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.roomId)
  return roomid_;
}
inline void SnapshotReq::set_roomid(::google::protobuf::uint32 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.roomId)
}

// optional fixed32 heroId = 2;
inline void SnapshotReq::clear_heroid() {
  heroid_ = 0u;
}
inline ::google::protobuf::uint32 SnapshotReq::heroid() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.heroId)
  return heroid_;
}
inline void SnapshotReq::set_heroid(::google::protobuf::uint32 value) {
  
  heroid_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.heroId)
}

// optional fixed32 attHeroId = 3;
inline void SnapshotReq::clear_attheroid() {
  attheroid_ = 0u;
}
inline ::google::protobuf::uint32 SnapshotReq::attheroid() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.attHeroId)
  return attheroid_;
}
inline void SnapshotReq::set_attheroid(::google::protobuf::uint32 value) {
  
  attheroid_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.attHeroId)
}

// optional float accSpeed = 4;
inline void SnapshotReq::clear_accspeed() {
  accspeed_ = 0;
}
inline float SnapshotReq::accspeed() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.accSpeed)
  return accspeed_;
}
inline void SnapshotReq::set_accspeed(float value) {
  
  accspeed_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.accSpeed)
}

// optional float x = 5;
inline void SnapshotReq::clear_x() {
  x_ = 0;
}
inline float SnapshotReq::x() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.x)
  return x_;
}
inline void SnapshotReq::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.x)
}

// optional float y = 6;
inline void SnapshotReq::clear_y() {
  y_ = 0;
}
inline float SnapshotReq::y() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.y)
  return y_;
}
inline void SnapshotReq::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.y)
}

// optional float vx = 7;
inline void SnapshotReq::clear_vx() {
  vx_ = 0;
}
inline float SnapshotReq::vx() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.vx)
  return vx_;
}
inline void SnapshotReq::set_vx(float value) {
  
  vx_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.vx)
}

// optional float vy = 8;
inline void SnapshotReq::clear_vy() {
  vy_ = 0;
}
inline float SnapshotReq::vy() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.vy)
  return vy_;
}
inline void SnapshotReq::set_vy(float value) {
  
  vy_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.vy)
}

// optional string version = 9;
inline void SnapshotReq::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SnapshotReq::version() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SnapshotReq::set_version(const ::std::string& value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SnapshotReq.version)
}
inline void SnapshotReq::set_version(const char* value) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SnapshotReq.version)
}
inline void SnapshotReq::set_version(const char* value, size_t size) {
  
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SnapshotReq.version)
}
inline ::std::string* SnapshotReq::mutable_version() {
  
  // @@protoc_insertion_point(field_mutable:SnapshotReq.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SnapshotReq::release_version() {
  // @@protoc_insertion_point(field_release:SnapshotReq.version)
  
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SnapshotReq::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    
  } else {
    
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:SnapshotReq.version)
}

// optional string taskId = 10;
inline void SnapshotReq::clear_taskid() {
  taskid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SnapshotReq::taskid() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.taskId)
  return taskid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SnapshotReq::set_taskid(const ::std::string& value) {
  
  taskid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:SnapshotReq.taskId)
}
inline void SnapshotReq::set_taskid(const char* value) {
  
  taskid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:SnapshotReq.taskId)
}
inline void SnapshotReq::set_taskid(const char* value, size_t size) {
  
  taskid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:SnapshotReq.taskId)
}
inline ::std::string* SnapshotReq::mutable_taskid() {
  
  // @@protoc_insertion_point(field_mutable:SnapshotReq.taskId)
  return taskid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SnapshotReq::release_taskid() {
  // @@protoc_insertion_point(field_release:SnapshotReq.taskId)
  
  return taskid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SnapshotReq::set_allocated_taskid(::std::string* taskid) {
  if (taskid != NULL) {
    
  } else {
    
  }
  taskid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), taskid);
  // @@protoc_insertion_point(field_set_allocated:SnapshotReq.taskId)
}

// optional fixed64 timestamp = 11;
inline void SnapshotReq::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 SnapshotReq::timestamp() const {
  // @@protoc_insertion_point(field_get:SnapshotReq.timestamp)
  return timestamp_;
}
inline void SnapshotReq::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:SnapshotReq.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SnapshotReq_2eproto__INCLUDED
